package com.dampyocalculator.cvbuilder.template;

import android.app.Activity;
import android.content.Context;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import androidx.activity.ComponentActivity;
import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import com.dampyocalculator.cvbuilder.R;
import com.dampyocalculator.cvbuilder.adapter.TmpAdapter;
import com.dampyocalculator.cvbuilder.database.DatabaseHandler;
import com.dampyocalculator.cvbuilder.database.usermodels;
import com.gkemon.XMLtoPDF.PdfGenerator;
import com.gkemon.XMLtoPDF.PdfGeneratorListener;
import com.gkemon.XMLtoPDF.model.FailureResponse;
import com.gkemon.XMLtoPDF.model.SuccessResponse;

import java.util.ArrayList;

public class TemplateFrag extends Fragment {
    private View finalInvoiceViewToPrint;

    TextView tv_nametmp, tv_posisitmp;
    Button generate;
    private ArrayList<usermodels> list = new ArrayList<>();
    private DatabaseHandler databaseHandler;
    Context context;
    ComponentActivity activity;
    private PdfGenerator.XmlToPDFLifecycleObserver xmlToPDFLifecycleObserver;
    RecyclerView rv_frag_exp_list;
    private TmpAdapter adapter;



    public TemplateFrag(ComponentActivity activity, Context context) {
        this.context = context;
        this.activity = activity;

    }

    private View createInvoiceViewFromRootView(View root) {
        finalInvoiceViewToPrint = root.findViewById(R.id.invoice_layout);
        tv_nametmp = (TextView) root.findViewById(R.id.tv_item_nama_tmp);
        tv_posisitmp = (TextView) root.findViewById(R.id.tv_item_posisi_tmp);
        rv_frag_exp_list = root.findViewById(R.id.rview_template);


        xmlToPDFLifecycleObserver = new PdfGenerator.XmlToPDFLifecycleObserver((ComponentActivity) activity);
        getLifecycle().addObserver(xmlToPDFLifecycleObserver);

        databaseHandler =new DatabaseHandler(context);
        adapter = new TmpAdapter(activity, context);
        databaseHandler.getReadableDatabase();
        list = databaseHandler.getAll();
        adapter.setListUser(list);
        RecyclerView.LayoutManager layoutManager = new LinearLayoutManager(context);
        rv_frag_exp_list.setLayoutManager(layoutManager);
        rv_frag_exp_list.setAdapter(adapter);



        return finalInvoiceViewToPrint;

    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View root = inflater.inflate(R.layout.invoice_layout, container, false);
        Button generate_invoice_btn = root.findViewById(R.id.generate_invoice_btn);


        finalInvoiceViewToPrint = createInvoiceViewFromRootView(root);


        generate_invoice_btn.setOnClickListener(v -> {
            generatePdf();
        });
        return root;
    }

    public void generatePdf() {
        PdfGenerator.getBuilder()
                .setContext(requireActivity())
                .fromViewSource()
                .fromView(finalInvoiceViewToPrint)
                /* "fromLayoutXML()" takes array of layout resources.
                 * You can also invoke "fromLayoutXMLList()" method here which takes list of layout resources instead of array. */
                /* It takes default page size like A4,A5. You can also set custom page size in pixel
                 * by calling ".setCustomPageSize(int widthInPX, int heightInPX)" here. */
                .setFileName("demo-invoice")
                /* It is file name */
                .setFolderNameOrPath("demo-invoice-folder/")
                /* It is folder name. If you set the folder name like this pattern (FolderA/FolderB/FolderC), then
                 * FolderA creates first.Then FolderB inside FolderB and also FolderC inside the FolderB and finally
                 * the pdf file named "Test-PDF.pdf" will be store inside the FolderB. */
                .actionAfterPDFGeneration(PdfGenerator.ActionAfterPDFGeneration.OPEN)
                .savePDFSharedStorage(xmlToPDFLifecycleObserver)
                /* It true then the generated pdf will be shown after generated. */
                .build(new PdfGeneratorListener() {
                    @Override
                    public void onFailure(FailureResponse failureResponse) {
                        super.onFailure(failureResponse);
                        Log.d("TAG", "onFailure: " + failureResponse.getErrorMessage());
                        /* If pdf is not generated by an error then you will findout the reason behind it
                         * from this FailureResponse. */
                        //Toast.makeText(MainActivity.this, "Failure : "+failureResponse.getErrorMessage(), Toast.LENGTH_SHORT).show();
                        Toast.makeText(getContext(), "" + failureResponse.getErrorMessage(), Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void showLog(String log) {
                        super.showLog(log);
                        Log.d("TAG", "log: " + log);
                        /*It shows logs of events inside the pdf generation process*/
                    }

                    @Override
                    public void onStartPDFGeneration() {

                    }

                    @Override
                    public void onFinishPDFGeneration() {

                    }

                    @Override
                    public void onSuccess(SuccessResponse response) {
                        super.onSuccess(response);
                        /* If PDF is generated successfully then you will find SuccessResponse
                         * which holds the PdfDocument,File and path (where generated pdf is stored)*/
                        //Toast.makeText(MainActivity.this, "Success", Toast.LENGTH_SHORT).show();
                        Log.d("TAG", "Success: " + response.getPath());

                    }
                });

    }
}
